# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import aidecomp_runtime_pb2 as aidecomp__runtime__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aidecomp_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIDecompRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeBinary = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/AnalyzeBinary',
                request_serializer=aidecomp__runtime__pb2.AnalyzeBinaryRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.AnalyzeBinaryResponse.FromString,
                _registered_method=True)
        self.GetProgramSummary = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/GetProgramSummary',
                request_serializer=aidecomp__runtime__pb2.GetProgramSummaryRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.GetProgramSummaryResponse.FromString,
                _registered_method=True)
        self.GetFunction = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/GetFunction',
                request_serializer=aidecomp__runtime__pb2.GetFunctionRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.GetFunctionResponse.FromString,
                _registered_method=True)
        self.GetCFG = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/GetCFG',
                request_serializer=aidecomp__runtime__pb2.GetCFGRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.GetCFGResponse.FromString,
                _registered_method=True)
        self.GetStackFrame = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/GetStackFrame',
                request_serializer=aidecomp__runtime__pb2.GetStackFrameRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.GetStackFrameResponse.FromString,
                _registered_method=True)
        self.GetExplanation = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/GetExplanation',
                request_serializer=aidecomp__runtime__pb2.GetExplanationRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.GetExplanationResponse.FromString,
                _registered_method=True)
        self.ApplyAnnotation = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/ApplyAnnotation',
                request_serializer=aidecomp__runtime__pb2.ApplyAnnotationRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.MutationResponse.FromString,
                _registered_method=True)
        self.ApplyRename = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/ApplyRename',
                request_serializer=aidecomp__runtime__pb2.ApplyRenameRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.MutationResponse.FromString,
                _registered_method=True)
        self.ApplyBookmark = channel.unary_unary(
                '/aidecomp.runtime.v1.AIDecompRuntime/ApplyBookmark',
                request_serializer=aidecomp__runtime__pb2.ApplyBookmarkRequest.SerializeToString,
                response_deserializer=aidecomp__runtime__pb2.MutationResponse.FromString,
                _registered_method=True)


class AIDecompRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgramSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCFG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStackFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExplanation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyAnnotation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyRename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyBookmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIDecompRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeBinary,
                    request_deserializer=aidecomp__runtime__pb2.AnalyzeBinaryRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.AnalyzeBinaryResponse.SerializeToString,
            ),
            'GetProgramSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgramSummary,
                    request_deserializer=aidecomp__runtime__pb2.GetProgramSummaryRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.GetProgramSummaryResponse.SerializeToString,
            ),
            'GetFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunction,
                    request_deserializer=aidecomp__runtime__pb2.GetFunctionRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.GetFunctionResponse.SerializeToString,
            ),
            'GetCFG': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCFG,
                    request_deserializer=aidecomp__runtime__pb2.GetCFGRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.GetCFGResponse.SerializeToString,
            ),
            'GetStackFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStackFrame,
                    request_deserializer=aidecomp__runtime__pb2.GetStackFrameRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.GetStackFrameResponse.SerializeToString,
            ),
            'GetExplanation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExplanation,
                    request_deserializer=aidecomp__runtime__pb2.GetExplanationRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.GetExplanationResponse.SerializeToString,
            ),
            'ApplyAnnotation': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyAnnotation,
                    request_deserializer=aidecomp__runtime__pb2.ApplyAnnotationRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.MutationResponse.SerializeToString,
            ),
            'ApplyRename': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyRename,
                    request_deserializer=aidecomp__runtime__pb2.ApplyRenameRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.MutationResponse.SerializeToString,
            ),
            'ApplyBookmark': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyBookmark,
                    request_deserializer=aidecomp__runtime__pb2.ApplyBookmarkRequest.FromString,
                    response_serializer=aidecomp__runtime__pb2.MutationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aidecomp.runtime.v1.AIDecompRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aidecomp.runtime.v1.AIDecompRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIDecompRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/AnalyzeBinary',
            aidecomp__runtime__pb2.AnalyzeBinaryRequest.SerializeToString,
            aidecomp__runtime__pb2.AnalyzeBinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgramSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/GetProgramSummary',
            aidecomp__runtime__pb2.GetProgramSummaryRequest.SerializeToString,
            aidecomp__runtime__pb2.GetProgramSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/GetFunction',
            aidecomp__runtime__pb2.GetFunctionRequest.SerializeToString,
            aidecomp__runtime__pb2.GetFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCFG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/GetCFG',
            aidecomp__runtime__pb2.GetCFGRequest.SerializeToString,
            aidecomp__runtime__pb2.GetCFGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStackFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/GetStackFrame',
            aidecomp__runtime__pb2.GetStackFrameRequest.SerializeToString,
            aidecomp__runtime__pb2.GetStackFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/GetExplanation',
            aidecomp__runtime__pb2.GetExplanationRequest.SerializeToString,
            aidecomp__runtime__pb2.GetExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyAnnotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/ApplyAnnotation',
            aidecomp__runtime__pb2.ApplyAnnotationRequest.SerializeToString,
            aidecomp__runtime__pb2.MutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyRename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/ApplyRename',
            aidecomp__runtime__pb2.ApplyRenameRequest.SerializeToString,
            aidecomp__runtime__pb2.MutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyBookmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aidecomp.runtime.v1.AIDecompRuntime/ApplyBookmark',
            aidecomp__runtime__pb2.ApplyBookmarkRequest.SerializeToString,
            aidecomp__runtime__pb2.MutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
